name: "MimmoSmart FRP Client"
slug: "mimmosmartaddon"
version: "1.0.5"
description: "Client FRP per l'accesso remoto sicuro"
url: "https://github.com/tarantinodomenico/mimmosmartaddon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: services
boot: auto
hassio_api: true
options:
  frp_server_addr: "api.stavebnitarantino.cz"
  frp_server_port: 7000
  frp_shared_token: ""
  local_ip: "127.0.0.1"
  local_port: 8123
  subdomain: ""
  custom_domain: ""
schema:
  frp_server_addr: str
  frp_server_port: int
  frp_shared_token: str
  local_ip: str
  local_port: int
  subdomain: str?
  custom_domain: str?
